### ISSUE TITLE
Adicionar o módulo do Instruction Memory e seu testbench

### ISSUE THREAD

**Issue by PedroAugustoStelzer0** [lucasmoraismt/MIPS_microprocessor#6]
Material de apoio:

![image](https://github.com/user-attachments/assets/9c8fd891-237f-43a1-9e2e-fd5a050a1379)

![image](https://github.com/user-attachments/assets/74cb3c91-6f1b-4320-b9b4-7f30031b271c)

**Comment by ifelp** [comment]
Já fiz esse!
